modLoader = "javafml"
loaderVersion = "[63,)"

[[mods]]
modId = "novisualdistractions"
version = "${version}"
displayName = "NoVisualDistractions"
logoFile = "icon.png"
description = "Removes visual distractions and annoying sounds"
