modLoader = "javafml"
loaderVersion = "[52,)"
license = "MIT"

[[mods]]
modId = "novisualdistractions"
version = "${version}"
displayName = "NoVisualDistractions"
logoFile = "icon.png"
credits = ""
authors = ""
description = "Removes visual distractions and annoying sounds"
